### ISSUE TITLE
Paypal-Checkout Button + popupBridge?

### ISSUE THREAD

**Issue by sidonaldson** [braintree/popup-bridge-android#15]
### General information

* SDK/Library version: Any
* Android Version and Device: Any

### Issue description

This is a query about integrating popup bridge and paypal using the Paypal-checkout Button component. Can you confirm whether the Button component already includes the popupbridge code - therefore the only work is to enable popupBridge inside the app itself?

**Comment by crookedneighbor** [comment]
Checkout.js already includes it. So yes, all you need to do is include popupbridge in your android app.

**Comment by quinnjn** [comment]
@sidonaldson for further clarification, there is a PR open (#14) that can be tested locally if you want to see how PopupBridge works with the PayPal Checkout button. 

We're having issues with Travis CI launching an emulator which is why the test is failing and it has not been merged yet.
