### ISSUE TITLE
Closing the newly opened webview from within

### ISSUE THREAD

**Issue by malua** [braintree/popup-bridge-android#27]
### General information

* SDK/Library version: 2.0.0
* Android Version and Device: Does not matter

### Issue description

Hey, first of all thanks for this nice plugin!
I have more of a question than an issue. I want to use this plugin to handle Payment Flows from within an webview and it works perfectly, except that I would need to close the openend webview from within.

The flow is like this:
I get an Redirect link from the payment provider and call `window['popupBridge'].open(redirectLink)` which opens the webview. unfortunately i cannot add `?popupBridgeReturnUrlPrefix` to the link as validation fails. 

after the user successfully authenticates and hits "Confirm" the payment provider redirects to a an success html file on our server. What I would like to do is, close the webview as soon as this success html file loads. this html file executs `window.close()` as soon as the page loads, but unfortunately i get 

> Scripts may close only the windows that were opened by it.

So my question is, if there is another way to close the webview from within?

If you have any idea, I would greatly appreciate your help!

**Comment by malua** [comment]
One follow up:
window.popupBridge is not available in the newly created webview, is it? otherwise i could probably create a new method like window.popupBrdige.close() and close the webview from the native part?

**Comment by sshropshire** [comment]
Hi @malua thanks for using the Braintree SDK for Android. Once the success.html file loads, you'll have to navigate back to your application using a deep link URL. Popup bridge does this by creating a custom URL scheme and registering it in your AndroidManifest.

From _success.html_, try setting `` location.href = `${YOUR_APPLICATION_ID}.popupbridge://success_callback`; `` to get back to your app. The result will then be forwarded to the originating WebView via the `window.popupBridge.onComplete` callback.

From the original WebView, you should then be able to communicate back into the native application using `window.popupBridge.sendMessage`. On the native side, a `PopupBridgeMessageListener` can listen for messages coming from the WebView. After parsing the message data, you can determine when the WebView should be closed.

**Comment by malua** [comment]
Thanks so much for you answer!
Setting the location.href in the success.html was actually enough. I thought i had to close it, as i could not pass the application id directly to the webview. But of course it's working when i hardcode the application id!

thank you!
