### ISSUE TITLE
Android 11 / API 30

### ISSUE THREAD

**Issue by malua** [braintree/popup-bridge-android#30]
### General information

* SDK/Library version: 2.0.0
* Android Version and Device: Pixel 3a API 30

### Issue description

Hey, just wanted to ask if it's on your radar, that popupBridge does not work on Android 11 / API 30? I just noticed that the popup browser doesn't open on an emulator with API 30, so I wanted to let you know. 

All the best,
Lukas

EDIT: I know android 11 is not even out yet ;)

**Comment by sshropshire** [comment]
Hi @malua thanks for using the Braintree SDK for Android. Android 11 has a more strict intent query system, and we have a [draft PR](https://github.com/braintree/browser-switch-android/pull/31) up that should resolve this issue once merged. We can leave this issue open for tracking, and we'll post an update here when it's ready.

**Comment by malua** [comment]
Great, thanks!

**Comment by sarahkoop** [comment]
Hi @malua, version `3.1.0` has been released and includes support for Android 11.

**Comment by malua** [comment]
Thanks for the update!
