### ISSUE TITLE
MavenRepository could not be resolved

### ISSUE THREAD

**Issue by danieledivito** [braintree/popup-bridge-android#4]
adding 
dependencies {
  compile 'com.braintreepayments:popupbridge:0.1.+'
}

to gradle return

Error:(46, 13) Failed to resolve: com.braintreepayments:popupbridge:0.1.+

this is my repositories:

repositories {
    mavenCentral()

}

**Comment by quinnjn** [comment]
@danieledivito thanks for the report! Our README is incorrect, we'll fix it soon.

The correct dependency is: `compile 'com.braintreepayments:popup-bridge:0.1.+'`

**Comment by quinnjn** [comment]
Fixed in 9c7241eeb6c89726bd8e6e81970afc586ed574b5
