### ISSUE TITLE
No import for "com.braintreepayments.popupbridge.PopupBridgeActivity"

### ISSUE THREAD

**Issue by JustTrust** [braintree/popup-bridge-android#54]
### General information

* Version 3.2.0
* Any version, any device

### Issue description

I started sdk implementation but faced with problem.
Fist: add link to sdk to build.gradle, used 3.2.0 because it marked as latest version
<img width="246" alt="image" src="https://user-images.githubusercontent.com/16021604/158387232-7ec24c39-efb9-4015-a989-e7d8bd39ad5a.png">

Second: add activity tag to manifest file but there is no import for
<img width="894" alt="image" src="https://user-images.githubusercontent.com/16021604/158387604-01ac5e08-23e6-4e9e-abc7-78c7ade93684.png">
"com.braintreepayments.popupbridge.PopupBridgeActivity"
And second step if failed here.

**Comment by sarahkoop** [comment]
Hi @JustTrust  - We released `3.2.0` recently to provide Android 12 support for the previous major version of this SDK, but `4.1.0` is the latest version. Updating to that version should resolve this issue.
