### ISSUE TITLE
PayPal web view does not closed and does not return to application with result

### ISSUE THREAD

**Issue by JustTrust** [braintree/popup-bridge-android#57]
### General information

* SDK version: 4.1.0
* Android Version - any, Device - any

### Code:

build.gradle
```
implementation 'com.braintreepayments.api:popup-bridge:4.1.0'
```

AndroidManifest.xml
```
        <activity
            android:name=".BrainTreeActivity"
            android:exported="true"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="popup_bridge_scheme" />
            </intent-filter>
        </activity>
```

Activity
```
class BrainTreeActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_brain_tree)
        println("BrainTreeActivity was called onCreate")
    }

    override fun onNewIntent(intent: Intent?) {
        super.onNewIntent(intent)
        println("BrainTreeActivity was called onNewIntent")
    }
}
```

WebView
```
class WebViewFragment : Fragment() {
    private var popupBridgeClient: PopupBridgeClient? = null
    private var webView: WebView? = null

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        activity?.let {
            popupBridgeClient = PopupBridgeClient(it, webView, "popup_bridge_scheme")
            popupBridgeClient?.setErrorListener { error: Exception -> println(error) }
        }
    }

    override fun onResume() {
        super.onResume()
        activity?.let{
            popupBridgeClient?.deliverPopupBridgeResult(it)
        }
    }
}
```

### Issue description

When press on PayPal button new BrainTree activity is open and showing a web view with PayPal page. Link is next 
```
https://www.sandbox.paypal.com/checkoutnow?fundingSource=paypal&token=EC-xxxxxxxxxxxxx&useraction=commit&redirect_uri=popup_bridge_scheme%3A%2F%2Fpopupbridgev1%2F&native_xo=1
```
When on PayPal page press PayNow web view does not closed and does not return to application with result. Instead it redirect on next page
```
https://www.sandbox.paypal.com/webapps/mpp/page-not-found
```

![paypal](https://user-images.githubusercontent.com/16021604/160582446-b6a14848-e14c-4f25-8595-3f289cce4e09.png)

**Comment by sarahkoop** [comment]
I think you are missing the [steps here](https://github.com/braintree/popup-bridge-android#using-paypal-in-a-webview) to set up a checkout page that uses the Braintree JS SDK or PayPal Checkout.js. 

If you do not have your own checkout page that uses one of those SDKs that you need to launch in a WebView, you can integrate PayPal payments directly into your app using the [Braintree Android SDK](https://github.com/braintree/braintree_android). This SDK launches the PayPal flow in a WebView and returns to your app upon completion. See documentation on that flow [here](https://developer.paypal.com/braintree/docs/guides/paypal/checkout-with-paypal/android/v4).

**Comment by JustTrust** [comment]
Thank you for bring my attention to this but we have our checkout page that uses paypal-checkout.min.js

**Comment by JustTrust** [comment]
Sure. Here it is:
`
async function initBraintreePaypal() {
    paypalLoading.next(true);
    clientTokenData = clientTokenData || await cashierPaymentDetailsDataService.getBraintreeClientToken(getPpmi());
    isVaulted.next(clientTokenData.IsVaulted);
    paypalLoading.next(false);
    return {
        paypal: initBraintreePaypalCheckoutInstance(
            clientTokenData.ClientToken,
            clientTokenData.ClientSdkUrl,
            clientTokenData.ClientPayPalSdkUrl,
            clientTokenData.ClientFraudToolSdkUrl,
            clientTokenData.IsVaulted,
            clientTokenData.IsCheckoutVaultSupported
        ),
        isVaulted: clientTokenData.IsVaulted,
        isCheckoutVaultSupported: clientTokenData.IsCheckoutVaultSupported
    };
}

async function initBraintreePaypalCheckoutInstance(
        clientToken,
        clientSdkUrl,
        PayPalSdkUrl,
        isVaulted,
        isCheckoutVaultSupported
    ) {
        await loadBraintreePaypalScript(PayPalSdkUrl);
        const clientInstance = await createBraintreeClientInstance(clientSdkUrl, clientToken);
        paypalCheckoutInstance = await paypalCheckoutInstance || await window.braintree.paypalCheckout.create({
            autoSetDataUserIdToken: isVaulted,
            client: clientInstance
        });

        let checkoutOptions;

        if (isCheckoutVaultSupported) {
            const dataAttributes = {
                commit: false
            };
            checkoutOptions = isVaulted
                ? {dataAttributes, 'disable-funding': 'card'}
                : {vault: true};
        } else {
            checkoutOptions = {
                intent: 'capture'
            };
        }

        return paypalCheckoutInstance.loadPayPalSDK(checkoutOptions);
    }
`

**Comment by crookedneighbor** [comment]
Sorry for the delay. One question I have for this is if the same behavior is experienced for you outside of a webview environment. If you launch this configuration in a normal web browser, do you experience the same error page? Or is it successful there.

I _think_ we're running into an unexpected and unhandled error in the PayPal flow here, which is why it's going to that https://www.sandbox.paypal.com/webapps/mpp/page-not-found page instead of correctly going to the right place.

**Comment by crookedneighbor** [comment]
We're forwarding this on to the team responsible for the PayPal flow generally to see if they have any particular insights about why your particular configuration would result in this. I see you're using the checkout with vault feature, and I think that code path has something to do with it.

**Comment by JustTrust** [comment]
We check it with the same configuration but using regular android web view without bridge and it works fine. But when we run it with bridge SDK it fails with same configuration and user.
In logs after payment is done we can see this failed request:
```
Request URL: https://www.sandbox.paypal.com/popup_bridge_scheme://popup_bridge_scheme/?token=EC-XXXXXXXXXXXXX&PayerID=XXXXXXXXXXXXXX&paymentId=PAYID-XXXXXXXXXXXXXXXXXXXX&intent=sale&opType=payment&return_uri=https%3A%2F%2Fwww.paypal.com%2Fcheckoutnow%2Ferror%3FpaymentId%3DPAYID-MJMTI7Y77W94549S8547633X%26token%3DEC-4N217176VT5755549%26PayerID%3DPESXBGDED6QE8%26paymentId%3DPAYID-MJMTI7Y77W94549S8547633X
Request Method: GET
Status Code: 404 
Referrer Policy: strict-origin-when-cross-origin
```

**Comment by JustTrust** [comment]
Is there any updates?

**Comment by JustTrust** [comment]
Thanks, it helps!
