### ISSUE TITLE
Popup-bridge-android cause conflicts with other flows 

### ISSUE THREAD

**Issue by iAmMarco1999** [braintree/popup-bridge-android#58]
### General information

* SDK/Library version: 
* Android Version and Device: 

### Issue description

Hi, I'm the developer From Xiaomi , I found Popup-bridge-android could cause conflicts with our other flows.

Above all, our main shopping flow is : **HomePage (Native) -> Product Page (H5) -> Cart Page (Native) -> CheckOut Page (H5) -> PayPal Page (Open in Browser) -> (Back) CheckOut Page (H5)**.

I understood that  _android:launchMode="singleTask"_   is necessary to make PayPal Page back to our App after finishing the process in browser. However, all our H5 page is WebActivity.   _android:launchMode="singleTask"_  blocks the Flow:  **Cart Page (Native) -> CheckOut Page (H5)**  because we have created a WebActivity in the step of  **Product Page (H5) -> Cart Page (Native)**.   SingleTask Launch mode will force App to reuse the same activity in Stack.

We've tried to created a new activity for the CheckOut Page but it didn't work as we expect. Though the main shopping flow could be executed successfully, there are some unpredictable problems happened (We don't want to manage 3 activities at the same time).  

I've noticed your Demo showed in the repository which contained two possible situations : "**Native activity - PopupBridge**" and "**WebView - PopupBridge**". But our flows are more complex, we have to manage Native activity and WebView activity in our shopping flow at the same time, this " launch mode : SingleTask"  is able to cause some conflicts.

Do you have any suitable solutions to this problem ?  If I didn't make myself understood, Please let me know.

**Comment by sshropshire** [comment]
Hi @iAmMarco1999 would `singleTop` work in this scenario? That would deep link back into the existing CheckoutOut Page without recreating the Activity. Then all that's needed is to override `onNewIntent`.

**Comment by iAmMarco1999** [comment]
Hi @sshropshire , I've tried this _singleTop_  before but it didn't work, which was not able to make App back from browser.

**Comment by sshropshire** [comment]
@iAmMarco1999 could you provide a small demo app reproducing the issue? If we simplify the flow we can isolate and better diagnose the issue.

**Comment by iAmMarco1999** [comment]
> @iAmMarco1999 could you provide a small demo app reproducing the issue? If we simplify the flow we can isolate and better diagnose the issue.

Hey, I forked your demo and have written a simple demo in my repo. You could have a look.

**Comment by sshropshire** [comment]
Hi @iAmMarco1999 thanks for this! I was OOO temporarily but I'm now back in the loop. What are the exact steps to reproduce the issue in the forked Demo?

**Comment by iAmMarco1999** [comment]
> Hi @iAmMarco1999 thanks for this! I was OOO temporarily but I'm now back in the loop. What are the exact steps to reproduce the issue in the forked Demo?

Just follow steps below:
1.click "Xiaomi_Test_This is our homepage" button
2.click "This is our product station page and I need to jump into Shopping Cart Page(Click)" button
3.click "This is our shopping cart page and I need to jump into our order page to check out(Click)" button
4.you will find the page jump back from the last page. Though I didn't add our order page to check out , the key of our problem has showed up. We have two different activities in our shopping flow , the "SingleTask" dosen't work for us.

**Comment by sshropshire** [comment]
@iAmMarco1999 I was able to set `intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP)` in `ShoppingCartActivity` as mentioned [here](https://stackoverflow.com/a/2427773). Does that work?

**Comment by iAmMarco1999** [comment]
> @iAmMarco1999 I was able to set `intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP)` in `ShoppingCartActivity` as mentioned [here](https://stackoverflow.com/a/2427773). Does that work?

I've tried your codes and some suggestions on stackoverflow. I didn't see any differences. It didn't work.

**Comment by sshropshire** [comment]
Hi @iAmMarco1999 can you try this fork I created with `FLAG_ACTIVITY_CLEAR_TOP`? https://github.com/sshropshire/popup-bridge-android-clear-top/tree/clear_top

**Comment by iAmMarco1999** [comment]
> Hi @iAmMarco1999 can you try this fork I created with `FLAG_ACTIVITY_CLEAR_TOP`? https://github.com/sshropshire/popup-bridge-android-clear-top/tree/clear_top

I've seen your changes in this fork and It didn't work for me

**Comment by iAmMarco1999** [comment]
> @iAmMarco1999 if you run the demo you can verify that in step 4 you are returned to the same activity created in step 2.
> 
> Since an instance of `ProductStationAndOrderPageActivity` already exists on the back stack, the `CLEAR_TOP` Intent flag will prevent a new instance from being created.

Yeah, That's the problem. We don't want to see this return happened in our demo. We expect our App to start  **a new order-page activity** which is the same activity with our **ProductStationAndOrderPageActivity**. So we always get back to our product station ,which already exists on the back stack, from our shoppingcart activity. 

I didn't code an order-page activity and I just want to show we always get back to **ProductStationAndOrderPageActivity**.

I‘ve tried your suggestions in our App. It still got back to the previous activity thought it didn't create a new instance. It didn't jump to our next order page.

**Comment by sshropshire** [comment]
@iAmMarco1999 understood. How about this?

```java
intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
```

It will clear all of the activities on the back stack and create a new instance of `ProductStationAndOrderPageActivity` to be set as the root activity. I updated the [forked repo](https://github.com/sshropshire/popup-bridge-android-clear-top/tree/clear_top) to use this method as well.

**Comment by iAmMarco1999** [comment]
> ```java
> intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
> ```

Hey ,I've tried your codes. It worked but it changed some backwards flows in our App. I need to communicate with our PM first since it's really difficult to find other ways ti solve this problem.
