### ISSUE TITLE
popupBridge.open() instead of window.open() in JS library

### ISSUE THREAD

**Issue by flaviolivolsi** [braintree/popup-bridge-android#6]
Hello,
I would like to implement popup bridge in an app that uses PayPal in a webview, but I noticed that in your [JS library](https://js.braintreegateway.com/js/braintree-2.31.0.js) the use of `window.open()` is forced and there is no trace of a popupBridge override. How do you suggest to proceed? Shall I just override `PopupView.prototype.open` in order to use popup bridge?
Thanks,
Flavio

**Comment by lilaconlee** [comment]
PopupBridge is only supported in v3 of [`braintree-web`](https://github.com/braintree/braintree-web) starting with [3.9.0](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#390) and we do not plan on adding support to v2. Sorry for any inconvenience!
