### ISSUE TITLE
Navigation is blocked, auto return sucks

### ISSUE THREAD

**Issue by pcicp** [braintree/popup-bridge-android#66]
![Screenshot_1671797307](https://user-images.githubusercontent.com/11014191/209333997-2f624337-0ccb-4e05-95c8-f58c625eb8e2.png)
### General information

* SDK/Library version: popup-bridge-4.1.0, browser-switch-2.3.2
* Android Version and Device: sdk 31, emulator Pixel 5 API 31

### Issue description

when i completed payment, paypal auto return sucks, can't close custom tabs and back to activity

inspect chrome, console warn:
Navigation is blocked: xxx.popupbridge://popupbridgev1/yyy&PayerID=aaa&st=Completed&tx=bbb&cc=USD&amt=0.01&cm=0%3B5&payer_email=ccc&payer_id=ddd&payer_status=VERIFIED&first_name=eee&last_name=fff&txn_id=ggg&mc_currency=USD&mc_fee=0.01&mc_gross=0.01&protection_eligibility=ELIGIBLE&payment_fee=0.01&payment_gross=0.01&payment_status=Completed&payment_type=instant&handling_amount=0.00&shipping=0.00&item_name=hhh&quantity=1&txn_type=web_accept&payment_date=iii&receiver_id=jjj&notify_version=UNVERSIONED&custom=kkk&invoice=mmm&verify_sign=nnn

AndroidManifest.xml:
`<activity android:name="yyyActivity"
    android:launchMode="singleTask"
    android:screenOrientation="portrait"
    android:exported="true">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <data android:scheme="xxx.popupbridge" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
    </intent-filter>
</activity>`

**Comment by sshropshire** [comment]
Hi @pcicp thanks for using the Braintree SDK for Android. This may be an issue with the PayPal JS SDK. Does this occur every time? Also can you provide a video of the steps taken to reproduce the issue? We can forward this video to the correct team.

**Comment by pcicp** [comment]
finally, i found it's caused by chrome security. i refer to https://github.com/EddyVerbruggen/Custom-URL-scheme/issues/156. 

our website used deprecated solution [PayPal Payments Standard HTML variables](https://developer.paypal.com/api/nvp-soap/paypal-payments-standard/integration-guide/Appx-websitestandard-htmlvariables/).

set a middle page as return url, not popupbridge url.
if user direct click paypal return, middle page load js to redirect popupbridge url.
if user wait paypal auto return countdown, middle page prompt user to click popupbridge url to avoid navigation blocked.
